#include <stdio.h>
#define SEPARATOR ','
#define QUOTE '"'

static const char* RES = "result\"";
static const char* MES = "message\"";
static const char* UID = "userIndex\"";

char result[15];
char messages[40];
char userIndex[200];

int readMessages(const char* input)
{
    const char* tmpptr = input;
    const char* tmpcmp;
    char* tmpwrt;
    int state = 0;
    while(*tmpptr != '\0')
    {
        switch (state) {
            case -1:
                /* Invalid Input */
                if (*tmpptr == SEPARATOR) state = 0;
                break;
            case 0: 
                if (*tmpptr == QUOTE) state = 1;
                break;
            case 1:
                switch(*tmpptr){
                    case 'r':
                        state = 10;
                        break;
                    case 'm':
                        state = 20;
                        break;
                    case 'u':
                        state = 30;
                        break;
                    default:
                        state = -1;
                }
                break;
            case 10:
                /* Entering result */
                tmpcmp = RES+1;
                while (*tmpptr != '\0' && *tmpcmp != '\0') {
                    if (*tmpptr != *tmpcmp) {
                        state = -1;
                        break;
                    }
                    ++tmpptr;
                    ++tmpcmp;
                }
                if (state == 10) state = 15;
                break;
            case 15:
                if (*tmpptr == QUOTE) state = 16;
                break;
            case 16:
                /* Reading result */
                tmpwrt = result;
                while (*tmpptr != QUOTE) {
                    if (*tmpptr == '\0') return -1;
                    *tmpwrt = *tmpptr;
                    ++tmpptr;
                    ++tmpwrt;
                }
                *tmpwrt = '\0';
                state = 0;
                break;
            case 20:
                /* Entering message */
                tmpcmp = MES+1;
                while (*tmpptr != '\0' && *tmpcmp != '\0') {
                    if (*tmpptr != *tmpcmp) {
                        state = -1;
                        break;
                    }
                    ++tmpptr;
                    ++tmpcmp;
                }
                if (state == 20) state = 25;
                break;
            case 25:
                if (*tmpptr == QUOTE) state = 26;
                break;
            case 26:
                /* Reading message */
                tmpwrt = messages;
                while (*tmpptr != QUOTE) {
                    if (*tmpptr == '\0') return -1;
                    *tmpwrt = *tmpptr;
                    ++tmpptr;
                    ++tmpwrt;
                }
                *tmpwrt = '\0';
                state = 0;
                break;
            case 30:
                /* Entering userIndex */
                tmpcmp = UID+1;
                while (*tmpptr != '\0' && *tmpcmp != '\0') {
                    if (*tmpptr != *tmpcmp) {
                        state = -1;
                        break;
                    }
                    ++tmpptr;
                    ++tmpcmp;
                }
                if (state == 30) state = 35;
                break;
            case 35:
                if (*tmpptr == QUOTE) state = 36;
                break;
            case 36:
                /* Reading userIndex */
                tmpwrt = userIndex;
                while (*tmpptr != QUOTE) {
                    if (*tmpptr == '\0') return -1;
                    *tmpwrt = *tmpptr;
                    ++tmpptr;
                    ++tmpwrt;
                }
                *tmpwrt = '\0';
                state = 0;
                break;
            default:
                ;
        }
        ++tmpptr;
    }
    return 0;
}
int getIndex(FILE* dataFile)
{
    /* This Function is Simplified for Specific Output Generated by Function recId and should not be Used Otherwise */
    char readptr;
    char* wrtptr;
    char lIndex[4];
    int lenIndex;
    int cnt;
    int cnt2;
    if (dataFile == NULL) return -1;
    cnt = 0;
    while ((readptr = getc(dataFile)) != EOF)
    {
        if (readptr == '=') ++cnt;
        if (cnt == 3) break;
    }
    if (cnt == 3) 
    {
        if (fgets(lIndex, 4, dataFile) == NULL) {
            printf("Error reading Index file!\n");
            fclose(dataFile);
            return -2;
        }
        lenIndex = atoi(lIndex);
        if (lenIndex >= 199) {
            printf("Wrong format of Index file!\n");
            fclose(dataFile);
            return -3;
        }
    }
    while ((readptr = getc(dataFile)) != EOF)
    {
        if (cnt == 4) break;
        if (readptr == '=') ++cnt;
    }
    if (cnt == 4)
    {
        cnt2 = 0;
        wrtptr = userIndex;
        while (cnt2 < lenIndex)
        {
            *wrtptr = readptr;
            ++wrtptr;
            ++cnt2;
            if ((readptr = getc(dataFile)) == EOF || readptr == '\n') break;
        }
        *wrtptr = '\0';
        return ++cnt2;
    }
    return -1;
}
